version: '3'

services:
  jenkins-master:
    build: .
    ports: 
      - "9090:8080"
      - "50000:50000"
    depends_on:
      - jenkins-data

  jenkins-data:
    build:
      context: ./
      dockerfile: Dockerfile-data